spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: rjsrjs12300 # 3
    password: xhva qydp ntih funv # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7s